dist: xenial
language: python
python:
  - "3.7-dev"	
  - "3.7"
# command to install dependencies
install:
  - pip install .
  - pip install mypy
script:
  # command to run tests
  - pytest
  # command to run mypy
  - mypy . --disallow-untyped-defs --ignore-missing-imports
