dist: xenial
language: python
python:
  - "3.7-dev"	
  - "3.8-dev"	
  - "nightly"
  - "3.7"
# command to install dependencies
install:
  - pip install .
# command to run tests
script: python -m pytest
