---

starting_with:
  data: composite
  schema: composite

steps:
  - Consume:
      name: ExportToCSV
      filename: 01_immutable_singleton.yaml
      columns:
        - immutable_block:
            - i_text_in_folder
