---

starting_with:
  data: composite
  schema: composite

steps:
  - Consume:
      name: ExportToCSV
      filename: 02_immutable_singleton_all_empty.yaml
      columns:
        - immutable_block:
            - i_text_never_populated
