---

starting_with:
  data: composite
  schema: composite

steps:
  - Consume:
      name: ExportToCSV
      filename: 05_temporal_list_and_immutable_keyed_list.csv
      columns:
        - temporal_block:
            - t_list_in_root:
                type: List
                children:
                  - t_text_in_list
        - immutable_block:
            - i_keyed_list_in_root:
                type: KeyedList
                children:
                  - i_text_in_keyed_list: special name