---

starting_with:
  data: composite
  schema: composite

steps:
  - Consume:
      name: ExportToCSV
      filename: 06_deep_nesting.csv
      columns:
        - immutable_block:
          - i_outer_nested_keyed_list:
              type: KeyedList
              children:
                - i_inner_nested_keyed_list:
                    type: KeyedList
                    children:
                      - i_text_in_inner_nested_keyed_list
                      - i_list_in_inner_nested_keyed_list:
                          type: List
                          children:
                            - i_text_in_list_in_inner_nested_keyed_list
                            - i_keyed_list_in_list_in_inner_nested_keyed_list:
                                type: KeyedList
                                children:
                                  - i_text_in_keyed_list_in_list_in_inner_nested_keyed_list
                - i_text_in_outer_nested_keyed_list
