starting_with:
  data: generic/origin
  schema: generic

resulting_in:
  data: generic/actual

steps:
  - Filter:
      name: LatestFilter
  - Filter:
      name: ImmutableValueThreshold

      threshold_var: immutable_var
      threshold: 7