starting_with:
  data: generic/origin
  schema: generic

resulting_in:
  data: generic/sequential

steps:
  - SequentialFilter:
    - LatestFilter: {}
    - ImmutableValueThreshold:
        threshold_var: immutable_var
        threshold: 7