from polytropos.actions.changes.stat.crosssectional.univariate import CrossSectionalMinimum
from polytropos.actions.changes.stat.crosssectional.univariate import CrossSectionalMaximum
from polytropos.actions.changes.stat.crosssectional.univariate import CrossSectionalMean
from polytropos.actions.changes.stat.crosssectional.univariate import CrossSectionalMedian
