from polytropos.actions.changes.stat.cross_sectional.univariate import CrossSectionalMinimum
from polytropos.actions.changes.stat.cross_sectional.univariate import CrossSectionalMaximum
from polytropos.actions.changes.stat.cross_sectional.univariate import CrossSectionalMean
from polytropos.actions.changes.stat.cross_sectional.univariate import CrossSectionalMedian
